# Generated by Django 5.2.3 on 2025-07-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('mileage', models.PositiveIntegerField(help_text='Пробіг автомобіля')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('gas', 'Gas')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('status', models.CharField(choices=[('in stock', 'In stock'), ('expiring', 'Expiring'), ('out of stock', 'Out of stock')], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carbrand')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carmodel')),
            ],
        ),
    ]
