# Generated by Django 5.2.3 on 2025-07-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
